<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5c421c82-101a-43cf-9939-50a612560e9f</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\CvEvaluator.Application\CvEvaluator.Application.csproj" />
    <ProjectReference Include="..\CvEvaluator.Infrastructure\CvEvaluator.Infrastructure.csproj" />
  </ItemGroup>

</Project>
